// ─── NSE Stock Universe ──────────────────────────────────────────────
// Comprehensive list: Nifty 50/100/200 + F&O + popular mid/small caps.
// This wide universe ensures we catch the same volume shockers
// that Chartink's scan finds across the entire cash segment.
// Chartink scan: ( {cash} ( daily volume > daily sma( volume,20 ) * 5 ) )

export const NSE_STOCKS: { ticker: string; name: string }[] = [
  // ── Nifty 50 ──
  { ticker: "RELIANCE", name: "Reliance Industries" },
  { ticker: "TCS", name: "Tata Consultancy Services" },
  { ticker: "HDFCBANK", name: "HDFC Bank" },
  { ticker: "INFY", name: "Infosys" },
  { ticker: "ICICIBANK", name: "ICICI Bank" },
  { ticker: "HINDUNILVR", name: "Hindustan Unilever" },
  { ticker: "SBIN", name: "State Bank of India" },
  { ticker: "BHARTIARTL", name: "Bharti Airtel" },
  { ticker: "ITC", name: "ITC" },
  { ticker: "KOTAKBANK", name: "Kotak Mahindra Bank" },
  { ticker: "LT", name: "Larsen & Toubro" },
  { ticker: "AXISBANK", name: "Axis Bank" },
  { ticker: "WIPRO", name: "Wipro" },
  { ticker: "HCLTECH", name: "HCL Technologies" },
  { ticker: "BAJFINANCE", name: "Bajaj Finance" },
  { ticker: "MARUTI", name: "Maruti Suzuki" },
  { ticker: "SUNPHARMA", name: "Sun Pharma" },
  { ticker: "TATAMOTORS", name: "Tata Motors" },
  { ticker: "TATASTEEL", name: "Tata Steel" },
  { ticker: "ADANIENT", name: "Adani Enterprises" },
  { ticker: "ASIANPAINT", name: "Asian Paints" },
  { ticker: "HINDALCO", name: "Hindalco Industries" },
  { ticker: "TITAN", name: "Titan Company" },
  { ticker: "DMART", name: "Avenue Supermarts" },
  { ticker: "POWERGRID", name: "Power Grid Corp" },
  { ticker: "NTPC", name: "NTPC" },
  { ticker: "ULTRACEMCO", name: "UltraTech Cement" },
  { ticker: "ONGC", name: "ONGC" },
  { ticker: "TATACONSUM", name: "Tata Consumer Products" },
  { ticker: "NESTLEIND", name: "Nestle India" },
  { ticker: "HDFCLIFE", name: "HDFC Life" },
  { ticker: "BAJAJFINSV", name: "Bajaj Finserv" },
  { ticker: "BRITANNIA", name: "Britannia" },
  { ticker: "CIPLA", name: "Cipla" },
  { ticker: "DRREDDY", name: "Dr Reddy's Labs" },
  { ticker: "EICHERMOT", name: "Eicher Motors" },
  { ticker: "GRASIM", name: "Grasim Industries" },
  { ticker: "HEROMOTOCO", name: "Hero MotoCorp" },
  { ticker: "HINDPETRO", name: "HPCL" },
  { ticker: "IOC", name: "Indian Oil Corp" },
  { ticker: "INDUSINDBK", name: "IndusInd Bank" },
  { ticker: "JSWSTEEL", name: "JSW Steel" },
  { ticker: "M_M", name: "Mahindra & Mahindra" },
  { ticker: "TECHM", name: "Tech Mahindra" },
  { ticker: "BPCL", name: "BPCL" },
  { ticker: "COALINDIA", name: "Coal India" },
  { ticker: "DIVISLAB", name: "Divi's Labs" },
  { ticker: "ESCORTS", name: "Escorts Kubota" },
  { ticker: "HAL", name: "HAL" },
  { ticker: "PIDILITIND", name: "Pidilite Industries" },
  { ticker: "SHRIRAMFIN", name: "Shriram Finance" },
  { ticker: "TRENT", name: "Trent" },
  { ticker: "VEDL", name: "Vedanta" },
  { ticker: "ZOMATO", name: "Zomato" },
  // ── Nifty Next 50 + popular midcaps ──
  { ticker: "ADANIPORTS", name: "Adani Ports" },
  { ticker: "AMBUJACEM", name: "Ambuja Cements" },
  { ticker: "APOLLOHOSP", name: "Apollo Hospitals" },
  { ticker: "AUROPHARMA", name: "Auro Pharma" },
  { ticker: "BAJAJAUTO", name: "Bajaj Auto" },
  { ticker: "BERGEPAINT", name: "Berger Paints" },
  { ticker: "BHARATFORG", name: "Bharat Forge" },
  { ticker: "BOSCHLTD", name: "Bosch" },
  { ticker: "CANBK", name: "Canara Bank" },
  { ticker: "CASTROLIND", name: "Castrol India" },
  { ticker: "CESC", name: "CESC" },
  { ticker: "DABUR", name: "Dabur" },
  { ticker: "DLF", name: "DLF" },
  { ticker: "GAIL", name: "GAIL India" },
  { ticker: "GODREJCP", name: "Godrej Consumer" },
  { ticker: "GRANULES", name: "Granules India" },
  { ticker: "GUJGASLTD", name: "Gujarat Gas" },
  { ticker: "HAVELLS", name: "Havells India" },
  { ticker: "HINDZINC", name: "Hindustan Zinc" },
  { ticker: "ICICIPRULI", name: "ICICI Prudential" },
  { ticker: "IDEA", name: "Vodafone Idea" },
  { ticker: "IGL", name: "Indraprastha Gas" },
  { ticker: "INDIAMART", name: "IndiaMART" },
  { ticker: "JINDALSTEL", name: "Jindal Steel" },
  { ticker: "JKCEMENT", name: "JK Cement" },
  { ticker: "JSWENERGY", name: "JSW Energy" },
  { ticker: "LALPATHLAB", name: "Lal PathLabs" },
  { ticker: "LAURUSLABS", name: "Laurus Labs" },
  { ticker: "LICHSGFIN", name: "LIC Housing" },
  { ticker: "LTIM", name: "LTIMindtree" },
  { ticker: "LUPIN", name: "Lupin" },
  { ticker: "MOTHERSUMI", name: "Mother Sumi" },
  { ticker: "MRF", name: "MRF" },
  { ticker: "MUTHOOTFIN", name: "Muthoot Finance" },
  { ticker: "NAUKRI", name: "Naukri" },
  { ticker: "NMDC", name: "NMDC" },
  { ticker: "OBEROIRLTY", name: "Oberoi Realty" },
  { ticker: "OFSS", name: "Oracle FS" },
  { ticker: "PETRONET", name: "Petronet LNG" },
  { ticker: "PNBHOUSING", name: "PNB Housing" },
  { ticker: "POLYCAB", name: "Polycab India" },
  { ticker: "PERSISTENT", name: "Persistent Systems" },
  { ticker: "RAMCOCEM", name: "Ramco Cements" },
  { ticker: "RBLBANK", name: "RBL Bank" },
  { ticker: "RECLTD", name: "REC" },
  { ticker: "SAIL", name: "SAIL" },
  { ticker: "SBILIFE", name: "SBI Life" },
  { ticker: "SHREECEM", name: "Shree Cement" },
  { ticker: "SIEMENS", name: "Siemens" },
  { ticker: "SRF", name: "SRF" },
  { ticker: "SUNTV", name: "Sun TV" },
  { ticker: "SYNGENE", name: "Syngene Intl" },
  { ticker: "TATAELXSI", name: "Tata Elxsi" },
  { ticker: "TATAPOWER", name: "Tata Power" },
  { ticker: "TORNTPHARM", name: "Torrent Pharma" },
  { ticker: "TVSMOTOR", name: "TVS Motor" },
  { ticker: "UBL", name: "United Breweries" },
  { ticker: "UNOMINDA", name: "Uno Minda" },
  { ticker: "VOLTAS", name: "Voltas" },
  { ticker: "WHIRLPOOL", name: "Whirlpool" },
  { ticker: "YESBANK", name: "Yes Bank" },
  { ticker: "ZEEL", name: "Zee Entertainment" },
  // ── F&O + small/mid caps (volume spike candidates) ──
  { ticker: "3MINDIA", name: "3M India" },
  { ticker: "AARTIDRUG", name: "Aarti Drugs" },
  { ticker: "ABB", name: "ABB India" },
  { ticker: "ABFRL", name: "Aditya Birla Fashion" },
  { ticker: "ADANIGREEN", name: "Adani Green" },
  { ticker: "ADANIPOWER", name: "Adani Power" },
  { ticker: "ADANITRANS", name: "Adani Trans" },
  { ticker: "AIAENG", name: "AIA Engineering" },
  { ticker: "AJANTPHARM", name: "Ajanta Pharma" },
  { ticker: "ALKEM", name: "Alkem Labs" },
  { ticker: "ALLCARGO", name: "Allcargo Logistics" },
  { ticker: "AMARAJABAT", name: "Amara Raja" },
  { ticker: "ANGELONE", name: "Angel One" },
  { ticker: "APARINDS", name: "Apar Industries" },
  { ticker: "ASHOKLEY", name: "Ashok Leyland" },
  { ticker: "ASTRAL", name: "Astral" },
  { ticker: "ATUL", name: "Atul" },
  { ticker: "AUBANK", name: "AU Small Finance Bank" },
  { ticker: "AVANTIFEED", name: "Avanti Feeds" },
  { ticker: "BALAMINES", name: "Balaji Amines" },
  { ticker: "BALRAMCHIN", name: "Balrampur Chini" },
  { ticker: "BANDHANBNK", name: "Bandhan Bank" },
  { ticker: "BANKBARODA", name: "Bank of Baroda" },
  { ticker: "BATAINDIA", name: "Bata India" },
  { ticker: "BDL", name: "Bharat Dynamics" },
  { ticker: "BEML", name: "BEML" },
  { ticker: "BIOCON", name: "Biocon" },
  { ticker: "BLUEDART", name: "Blue Dart" },
  { ticker: "BLUESTARCO", name: "Blue Star" },
  { ticker: "BRIGADE", name: "Brigade Ent" },
  { ticker: "CAMS", name: "CAMS" },
  { ticker: "CAPLIPOINT", name: "Caplin Point" },
  { ticker: "CEATLTD", name: "CEAT" },
  { ticker: "CENTURYPLY", name: "Century Plyboards" },
  { ticker: "CIGNITI", name: "Cigniti Technologies" },
  { ticker: "COROMANDEL", name: "Coromandel Intl" },
  { ticker: "CUMMINSIND", name: "Cummins India" },
  { ticker: "DATAPATTNS", name: "Data Patterns" },
  { ticker: "EDELWEISS", name: "Edelweiss Financial" },
  { ticker: "EMAMILTD", name: "Emami" },
  { ticker: "ENDURANCE", name: "Endurance Technologies" },
  { ticker: "EXIDEIND", name: "Exide Industries" },
  { ticker: "FEDERALBNK", name: "Federal Bank" },
  { ticker: "GLENMARK", name: "Glenmark Pharma" },
  { ticker: "GLAXO", name: "GSK Pharma" },
  { ticker: "GODFRYPHLP", name: "Godrej Agrovet" },
  { ticker: "GRAPHITE", name: "Graphite India" },
  { ticker: "GUJALKALI", name: "Gujarat Alkalies" },
  { ticker: "HEG", name: "HEG" },
  { ticker: "HIMADRI", name: "Himadri Speciality" },
  { ticker: "HONAUT", name: "Honda India Power" },
  { ticker: "IBULHSGFIN", name: "Indiabulls Housing" },
  { ticker: "IDBI", name: "IDBI Bank" },
  { ticker: "IDFC", name: "IDFC First Bank" },
  { ticker: "INDIGO", name: "IndiGo Airlines" },
  { ticker: "INDUSTOWER", name: "Indus Towers" },
  { ticker: "INTELLECT", name: "Intellect Design" },
  { ticker: "JBM", name: "JBM Auto" },
  { ticker: "JINDALSAW", name: "Jindal Saw" },
  { ticker: "JSWINFRA", name: "JSW Infra" },
  { ticker: "JUBLFOOD", name: "Jubilant Foodworks" },
  { ticker: "JUBLPHARMA", name: "Jubilant Pharma" },
  { ticker: "JUSTDIAL", name: "Just Dial" },
  { ticker: "KNRCON", name: "KNR Construction" },
  { ticker: "L&TFH", name: "L&T Finance" },
  { ticker: "LINDEINDIA", name: "Linde India" },
  { ticker: "MANAPPURAM", name: "Manappuram Finance" },
  { ticker: "MCX", name: "MCX India" },
  { ticker: "MGL", name: "Mahanagar Gas" },
  { ticker: "MPHASIS", name: "Mphasis" },
  { ticker: "NATIONALUM", name: "National Aluminium" },
  { ticker: "NAVINFLUOR", name: "Navin Fluorine" },
  { ticker: "NETWORK18", name: "Network18 Media" },
  { ticker: "NIACL", name: "New India Assurance" },
  { ticker: "NURECA", name: "Nureca Ltd" },
  { ticker: "OLECTRA", name: "Olectra Greentech" },
  { ticker: "PAGEIND", name: "Page Industries" },
  { ticker: "PGHL", name: "P&G Health" },
  { ticker: "PHOENIXLTD", name: "Phoenix Mills" },
  { ticker: "PFC", name: "PFC" },
  { ticker: "PNB", name: "Punjab Natl Bank" },
  { ticker: "POONAWALLA", name: "Poonawalla Fincorp" },
  { ticker: "PRAJINDS", name: "Praj Industries" },
  { ticker: "PREMIERENE", name: "Premier Energies" },
  { ticker: "PSPPRIME", name: "PSP Projects" },
  { ticker: "RAJESHEXPO", name: "Rajesh Exports" },
  { ticker: 